name: React CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --watchAll=false

    - name: Build App
      run: npm run build

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-ci-cd-app:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-ci-cd-app:latest

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Image
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/react-ci-cd-app:latest ghcr.io/${{ github.repository }}/react-ci-cd-app:latest

    - name: Push to GHCR
      run: docker push ghcr.io/${{ github.repository }}/react-ci-cd-app:latest

    - name: Notify
      run: echo "✅ Deployment Successful!"
